function ita() {
  var a = document.getElementById;
  document.getElementById('title').innerHTML = 'dietro lo schermo';
  document.getElementById('tale1').innerHTML = 'una';
  document.getElementById('tale2').innerHTML = 'storia';
  document.getElementById('tale3').innerHTML = 'di';
  document.getElementById('tale4').innerHTML = 'hyperfocusing';
  document.getElementById('intro-to-bio').innerHTML = 'Se sei il genere di persona che vuole conoscere <em>chi</em> lavora per lei personalmente, o semplicemente ti sei imbattuto in questo portfolio ed sei curioso di saperne di più su chi "Kali" sia, questa è la pagina per te!';
  document.getElementById('intro-to-bio2').innerHTML = "Ora, il tono potrà non essere sempre dei più seri, non sarebbe una biografia onesta se non esprimesse il mio senso dell'umorismo o non mostrasse i miei interessi più frivoli, ma spero che questa pagina dimostri anche che quando amo qualcosa, non importa se sia un hobby on un lavoro, la <em>amo</em> e ce la metterò tutta.<br>Se questa pagina ti comunicherà qualcosa, lascia che sia come io dedichi tutta me stessa a tutto ciò che faccio.";
  document.getElementById('click').innerHTML = "clicca su un argomento per saperne di più!";
  document.getElementById('clickandscroll').innerHTML = "clicca su un argomento e scrolla per saperne di più!";
  document.getElementById('steam').innerHTML = "videogames";
  document.getElementById('steam').nextElementSibling.innerHTML = "appena comincio un nuovo gioco scompaio nel nulla tanto quanto quando inizio un nuovo blog: Skyrim, Dragon Age, Final Fantasy, Tomb Raider... Preferisco giochi lunghi, possibilmente con seguiti che hanno con gli stessi personaggi o almeno gli stessi temi, e che non sono troppo difficili da completare perché in qualche modo crescendo ho perso tutte le mie abilità. Ero meravigliosa agli sparatutto e ai giochi di lotta, ora non posso neanche guardare nella direzione di Call of Duty!";
  document.getElementById('dog').innerHTML = "animali";
  document.getElementById('dog').nextElementSibling.innerHTML = "non vi mentirò: 95% del mio instagram è dedicato a pagine di cani, gatti, lontre e animali carini perchè mi migliorano la giornata. Mi serve la carica? Un po' di musica allegra, qualche cagnolino in costume e sono pronta a partire!";
  document.getElementById('bread').innerHTML = "cibo";
  document.getElementById('bread').nextElementSibling.innerHTML = "se c'è una cosa che mi rende una italiana da stereotipo è la mia relazione con il cibo. Sapete quelle battute su come le nonne italiane vi chiederanno di prendere il cosciotto di pollo da un pollo che ha vissuto in una montagna specifica e che è stato preservato in un luogo segreto, al buio, per non meno di sei mesi? Ecco, sono quella nonna. Sono così specifica su che cibo voglio, e mi godo ogni secondo di ogni pasto, purché sia composto di pietanze che mi piacciano, e odierò ogni secondo del pasto se c'è qualcosa che non mi piace tanto ma che ho scelto di mangiare perchè fa bene alla salute. Nessuna via di mezzo";
  document.getElementById('writing').innerHTML = "scrivere";
  document.getElementById('writing').nextElementSibling.innerHTML = "Mi sono ritrovata a scrivere storie originali (e ammettiamolo, molti clichè) alle scuole medie, e ciò si è evoluto nello scrivere fanfiction (che significa: odio quello che è successo a quel personaggio, scriverò io una strada migliore per lui), che è poi diventato scrittura collaborativa su tumblr, dove mi sono divertita tantissimo a creare personaggi che potevano esistere in un mondo predefinito e a inventarmi il loro mondo interiore, il loro sviluppo e le loro reazioni a ciò che altre persone scrivevano. Più o meno come scrivere telefilm, eccetto che invece che concentrarmi su un solo personaggio ne ho scritto una dozzina, e alcuni sono durati anche per più di sei anni. Ciò mi ha anche portata a volere che ogni personaggio avesse un blog tutto suo che lo rispecchiasse - e ho incontrato HTML e CSS per la prima volta!";
  document.getElementById('blogging').nextElementSibling.innerHTML = "tumblr mi piace non soltanto per le opportunità di apprendimento che offre - web designers e programmatori che offrono tutorial gratuiti per pura passione, io che imparo meglio l'inglese tramite la scrittura - ma anche pèrchè dà la chance di connettersi con persone ovunque nel mondo e conoscere culture, comunità, e sentire discussioni su argomenti rari e poco conosciuti che non avvengono da nessun'altra parte."
  document.getElementById('lang').innerHTML = "lingue";
  document.getElementById('lang').nextElementSibling.innerHTML = "sono Italiana, l'inglese è la mia seconda lingua, e sto cominciando a dare una prima occhiata alla grammatica spagnola, anche se purtroppo le giornate sono corte e ho dovuto scegliere e dare priorità alla programmazione. Ammiro e voglio imitare le persone che conoscono 5-6 lingue, perchè so quante porte mi abbia aperto il sapere l'inglese. Mi ha anche portata su tumblr, che a sua volta mi ha portata a capire meglio molti argomenti tra cui la psicologia, ma anche a interessarmi al web design, photoshop, e a seguire corsi che mi hanno poi fatto notare ambiti come l'analisi dei dati e le risorse umane. Mi ha anche fatto scrivere più di prima, ricordandomi quanto mi interessino anche le altre lingue, e così via."
  document.getElementById('tv').nextElementSibling.innerHTML = "Non sono mai stata una bambina sportiva (scioccante, lo so), ho preferito la tv. Buffy l'ammazzavampire è ciò che mi ha insegnato come comunicare in un inglese non rigido e che proveniva direttamente dai libri scolastici, perchè lo amavo così tanto che ho sentito il dovere di guardarlo e riguardarlo in lingua originale con i sottotitoli. Anche se guardo ancora sci-fi e telefilm drammatici, negli ultimi anni mi sono concentrata sulle sitcom e commedie, che trovo un ottimo modo di rilassarsi nel tempo libero, con tutta la loro leggerezza e ottimismo. Friends, Will&Grace, Scrubs, Una Mamma per Amica, Leverage e altri vecchi show spesso accompagno i miei pasti: è inspiegabile ma c'è sempre 'troppo da fare' per guardare un film da 90 minuti, mentre 5 episodi di fila di una sitcom sono okay."
  document.getElementById('books').innerHTML = "libri";
  document.getElementById('books').nextElementSibling.innerHTML = "Non ero soltanto una bambina da tv, ero anche quella che si dimenticava del mondo mentre leggeva finchè qualcuno non riusciva a recuperarne l'attenzione. Ho sempre letto troppo in fretta quindi mi ritrovavo sempre con nulla di nuovo da leggere: Jurassic Park, il primo libro che mi è stato regalato, mi è durato circa sei ore. Le superiori erano dedicate a Stephen King, Terry Pratchett e il Signore Degli Anelli, che avrò riletto un milione di volte. Anche i manga, nessuna vergogna nelle letture leggere e a volte ridicole, anche se c'è stato soltanto Gintama in quel campo negli ultimi anni.";
  document.getElementById('data').innerHTML = "analisi dei dati";
  document.getElementById('data').nextElementSibling.innerHTML = "";


}