function ita() {
  document.getElementById('title').innerHTML = "progetti futuri e passati";
  document.getElementById('subtitle').innerHTML = "mi potete trovare anche su tumblr, dove creo blog, gifset e modifico immagini - come vedrete scrollando questa pagina";
  document.getElementById('intro').innerHTML = "I prossimi blog si adattano a qualsiasi tipo di schermo, e offrono l'opzione di scegliere colori, la maggior parte dei font e le immagini già dalla pagina delle impostazioni di tumblr, senza che ci sia bisogno di conoscere l'html - con l'eccezione dei primi due blog che ho creato, qui solo per mostrare qualche extra<span id='sentimental'>... e perchè sono sentimentale</span>";
  document.getElementById('descr1').innerHTML = "uno dei miei blog più famosi, inspirato a Final Fantasy - come potete leggere anche sulla gif, i vostri lettori potranno passare in modalità notte o giorno con un click. C'è un menù a discesa, le barre laterali si spostano in alto negli schermi più piccoli, si possono unire colori a fondi, e ci sono i vecchi cari titoli con decorazioni!";
  document.getElementById('descr2').innerhtml = "un altro esempio di come potete personalizzare il blog precedente!"
  document.getElementById('descr3').innerhtml = "un blog a tema lgbtqia+, specificatamente è dedicato alla comunità aro-ace! Con una playlist e uno sfondo che cambia ogni volta che aggiornate la pagina";
  document.getElementById('descr4').innerhtml = "blog inspirato al Signore Degli Anelli! Questa anteprima è la visuale dalla pagina delle impostazioni di tumblr, per mostrare come ci sia anche l'opzione per trasformare i link da numeri romani a nazgul che si affacciano dalla barra laterale, e come si possa cambiare la posizione dello sfondo del banner con un click!"
  document.getElementById('descr5').innerhtml = "blog inspirato a super Mario! Naturalmente tutto ciò che si muove è un link, ma in ogni caso, non è sufficiente anche solo dire 'blog inspirato a super Mario'?";
  document.getElementById('descr6').innerhtml = "potere scegliere se avere un banner o no, numero di barre laterali e così via, in più potete scrivere i vostri aggiornamenti e ciò volete aggiungere alle barre direttamente dalla pagina di impostazioni senza bisogno di andare a modificare l'html!";
  document.getElementById('descr7').innerhtml = "stesso blog di prima, un esempio di come cambiando qualche colore e giocando con le opzioni gli si possa dare un look completamente personalizzato";
  document.getElementById('descr8').innerhtml = "un blog dove ho usato il pulsante per la modalità notte per trasformare l'intero blog, dandogli sfondi e immagini diverse. Il secondo blog che ho creato (e in quanto tale non si adatta agli schermi dei cellulari)";
  document.getElementById('descr9').innerhtml = "stesso blog di prima, un esempio di come un fan di Doctor Who potrebbe sfruttare l'opzione notte";
  document.getElementById('descr10').innerhtml = "ultimo e, ironicamente, il primo blog che ho mai creato: anche questo non si adatta a schermi piccoli, ma ha un posto speciale nel muo cuore... e a chi non piacciono i popup di navigazione e le stelle? ";
  document.getElementById('free').innerHTML = "tutti questi blog sono gratis e li potete trovare anche nella mia pagina <a href='https://ko-fi.com/kalipinna'>ko-fi</a>!";
  document.getElementById('soon').innerHTML = "in arrivo:";
  document.getElementById('figcaption').innerHTML = "un blog che dovrebbe ricordare la schermata dei videogiochi in cui si sceglie il proprio personaggio: un click sulla piccola anteprima mostrerà l'immagine e descrizione corrispondenti. Bottone per modalità giorno/notte incluso!";
  document.getElementById('butthen').innerHTML = "<em>ma allora</em>,<span id='youcould'> potresti chiederti,</span> <em>perchè ti sei iscritta a un corso di *introduzione* al web design?</em>";
  document.getElementById('because').innerHTML = "perché:<ol><li>Ho imparato ciò che so modificando l'html dei blog altrui e volevo scoprire quali regole di base mi sono persa</li><li>i blog su tumblr vanno creati seguendo le regole e lo stile tipico di tumblr, con la sua documentazione e html che è specifico di tumblr</li><li>... fare coding è così <span id ='fun' style ='font-style:italic;text-decoration: underline; font-family:underground;display:inline-block; font-size:2.5rem;'> divertente </span> e ogni scusa è buona per farlo</li></ol><br>";
  document.getElementById('happier').innerHTML = "non troverai qualcuno più felice di fare blog!";
  document.getElementById('credits').innerHTML = "crediti";
  document.getElementById('p1').innerHTML = "icone:fontawesome<br>Chocobo animato da <a href='https://gifer.com/en/4qGj' target='_blank'>@gifer</a>fonts da google e 1001fonts.";
  document.getElementById('p2').innerHTML = "script per le animazioni quando si scrolla da <a href='http://jsfiddle.net/ravimallya/mhfcwyk8/1/' target='_blank'>@ravimallya</a><br> immagini di sfondo e gif decorative rispettivamente da <a href='https://scottvandyne.tumblr.com' target='_blank'>scottvandyne</a> (la prima e ultima), me (sfondi di mezzo), e kaeeveoh-art (decorazioni)";
}

function eng() {
  document.getElementById('title').innerHTML = "past and future projects";
  document.getElementById('subtitle').innerHTML = "you'll find me on tumblr too, making themes/blogs, edits, giftsets and manips on my spare time - see some examples below";
  document.getElementById('intro').innerHTML = "The following themes will look good on screens of every width, and give you the options to pick colors, most fonts and all images straight from the customization page, so they can be personalized by anyone regardless of their knowledge in coding - with the exception of the very first ones I made, here to showcase some gadgets<span id='sentimental'>... and for sentimental reasons.</span>";
  document.getElementById('descr1').innerHTML = "one of my most famous themes, final fantasy inspired - as it says in the preview, your readers can go in dark or light mode with one click, there is a dropdown menu on one side, sidebars move on top on small screens, blending colors and backgrounds, and good old fancy titles!";
  document.getElementById('descr2').innerhtml = "another example of how the previous theme can be customized!";
  document.getElementById('descr3').innerhtml = "lgbtqia+ theme, specifically dedicated to the aro-ace community! With playlist at the bottom and a background that changes every time you refresh the page";
  document.getElementById('descr4').innerhtml = "lotr theme! preview image from the customization page to show how you can pick if you want animated moving nazguls as your links or regular roman numbers, as well as picking the position and size of your banner image!";
  document.getElementById('descr5').innerhtml = "my Super Mario-inspired theme! naturally everything that moves is a link, but really, isn't saying 'super Mario' enough? ";
  document.getElementById('descr6').innerhtml = "Optional banner, number of columns and so on, plus all updates and column text can be added directly from the customization page, no need to touch the code ";
  document.getElementById('descr7').innerhtml = "Same theme as before, just a little example of how simply picking a few different options can start giving it a much more personalized, different look";
  document.getElementById('descr8').innerhtml = "a theme where I played with the dark-mode button so that on top of it, your reader can actually enjoy a second theme - also a little image of your choosing will separate your posts. The second theme I've ever made (and as such not responsive for mobile)"
  document.getElementById('descr9').innerhtml = "another example of the previous theme, specifically of how it could be edited and customized by a Doctor Who fan."
  document.getElementById('descr10').innerHTML = "last, ironically, my very first theme: also not responsive, but it has a very special place in my heart... and who doesn't like popup navigation menus and stars? ";
  document.getElementById('free').innerHTML = "all of them are free and can also be found in my <a href='https://ko-fi.com/kalipinna'>ko-fi</a> page!";
  document.getElementById('soon').innerHTML = "coming soon:";
  document.getElementById('figcaption').innerHTML = "a theme meant to remind you of 'pick your character' screens in videogames, in which a click on the small preview will bring up the corresponding description and image. Dark mode/light mode button included!";
  document.getElementById('butthen').innerHTML = "<em>but then</em>,<span id='youcould'> you could ask,</span> <em>why did you take an *introduction* to web design course?";
  document.getElementById('because').innerHTML = "because:<ol><li>I learned what I know by editing other people's codes and I wanted to see what basic rules I had missed</li><li>tumblr coding means following tumblr styles and it has its own special html</li> <li>... coding is so much <span id='fun' style='font-style:italic;text-decoration: underline; font-family:underground;display:inline-block; font-size:2.5rem;'>fun</span> and I'll take any excuse to do it more</li></ol><br>";
  document.getElementById('happier').innerHTML = "you won't find someone happier to code for you!";
  document.getElementById('credits').innerHTML = "credits";
  document.getElementById('p1').innerHTML = "icons: fontawesome <br> animated Chocobo @<a href='https://gifer.com/en/4qGj' target='_blank'>gifer</a> <br> fonts:google fonts and 1001 fonts</p>";
  document.getElementById('p2').innerHTML = "script for animations happening on scroll by <a href='https://jsfiddle.net/ravimallya/mhfcwyk8/1/' target='_blank'>@ravimallya</a><br> background and decorative gifs by <a href='https://scottvandyne.tumblr.com' target='_blank'>scottvandyne</a> (first and last), me (second and third), and kaeeveoh-art(decorations).";
}