function ita() {
  document.getElementById('title').innerHTML = 'dietro lo schermo';
  document.getElementById('tale1').innerHTML = 'una';
  document.getElementById('tale2').innerHTML = 'storia';
  document.getElementById('tale3').innerHTML = 'di';
  document.getElementById('tale4').innerHTML = 'hyperfocusing';
  document.getElementById('intro-to-bio').innerHTML = 'Se sei il genere di persona che vuole conoscere <em>chi</em> lavora per lei personalmente, o semplicemente ti sei imbattuto in questo portfolio ed sei curioso di saperne di più su chi "Kali" sia, questa è la pagina per te!';
  document.getElementById('intro-to-bio2').innerHTML = "Ora, il tono potrà non essere sempre dei più seri, non sarebbe una biografia onesta se non esprimesse il mio senso dell'umorismo o non mostrasse i miei interessi più frivoli, ma spero che questa pagina dimostri anche che quando amo qualcosa, non importa se sia un hobby on un lavoro, la <em>amo</em> e ce la metterò tutta.<br>Se questa pagina ti comunicherà qualcosa, lascia che sia come io dedichi tutta me stessa a tutto ciò che faccio.";
  document.getElementById('click').innerHTML = "clicca su un argomento per saperne di più!";
  document.getElementById('clickandscroll').innerHTML = "clicca su un argomento e scrolla per saperne di più!";
  document.getElementById('steam').nextElementSibling.innerHTML = "appena comincio un nuovo gioco scompaio nel nulla tanto quanto quando inizio un nuovo blog: Skyrim, Dragon Age, Final Fantasy, Tomb Raider... Preferisco giochi lunghi, possibilmente con seguiti che hanno con gli stessi personaggi o almeno gli stessi temi, e che non sono troppo difficili da completare perché in qualche modo crescendo ho perso tutte le mie abilità. Ero meravigliosa agli sparatutto e ai giochi di lotta, ora non posso neanche guardare nella direzione di Call of Duty!";
  document.getElementById('dog').innerHTML = "animali";
  document.getElementById('dog').nextElementSibling.innerHTML = "non vi mentirò: 95% del mio instagram è dedicato a pagine di cani, gatti, lontre e animali carini perchè mi migliorano la giornata. Mi serve la carica? Un po' di musica allegra, qualche cagnolino in costume e sono pronta a partire!";
  document.getElementById('bread').innerHTML = "cibo";
  document.getElementById('bread').nextElementSibling.innerHTML = "se c'è una cosa che mi rende una italiana da stereotipo è la mia relazione con il cibo. Sapete quelle battute su come le nonne italiane vi chiederanno di prendere il cosciotto di pollo da un pollo che ha vissuto in una montagna specifica e che è stato preservato in un luogo segreto, al buio, per non meno di sei mesi? Ecco, sono quella nonna. Sono così specifica su che cibo voglio, e mi godo ogni secondo di ogni pasto, purché sia composto di pietanze che mi piacciano, e odierò ogni secondo del pasto se c'è qualcosa che non mi piace tanto ma che ho scelto di mangiare perchè fa bene alla salute. Nessuna via di mezzo";
  document.getElementById('writing').innerHTML = " scrivere";
  document.getElementById('writing').nextElementSibling.innerHTML = "Mi sono ritrovata a scrivere storie originali (e ammettiamolo, molti clichè) alle scuole medie, e ciò si è evoluto nello scrivere fanfiction (che significa: odio quello che è successo a quel personaggio, scriverò io una strada migliore per lui), che è poi diventato scrittura collaborativa su tumblr, dove mi sono divertita tantissimo a creare personaggi che potevano esistere in un mondo predefinito e a inventarmi il loro mondo interiore, il loro sviluppo e le loro reazioni a ciò che altre persone scrivevano. Più o meno come scrivere telefilm, eccetto che invece che concentrarmi su un solo personaggio ne ho scritto una dozzina, e alcuni sono durati anche per più di sei anni. Ciò mi ha anche portata a volere che ogni personaggio avesse un blog tutto suo che lo rispecchiasse - e ho incontrato HTML e CSS per la prima volta!";
  document.getElementById('blogging').nextElementSibling.innerHTML = "tumblr mi piace non soltanto per le opportunità di apprendimento che offre - web designers e programmatori che offrono tutorial gratuiti per pura passione, io che imparo meglio l'inglese tramite la scrittura - ma anche pèrchè dà la chance di connettersi con persone ovunque nel mondo e conoscere culture, comunità, e sentire discussioni su argomenti rari e poco conosciuti che non avvengono da nessun'altra parte."
  document.getElementById('lang').innerHTML = "lingue";
  document.getElementById('lang').nextElementSibling.innerHTML = "sono Italiana, l'inglese è la mia seconda lingua, e sto cominciando a dare una prima occhiata alla grammatica spagnola, anche se purtroppo le giornate sono corte e ho dovuto scegliere e dare priorità alla programmazione. Ammiro e voglio imitare le persone che conoscono 5-6 lingue, perchè so quante porte mi abbia aperto il sapere l'inglese. Mi ha anche portata su tumblr, che a sua volta mi ha portata a capire meglio molti argomenti tra cui la psicologia, ma anche a interessarmi al web design, photoshop, e a seguire corsi che mi hanno poi fatto notare ambiti come l'analisi dei dati e le risorse umane. Mi ha anche fatto scrivere più di prima, ricordandomi quanto mi interessino anche le altre lingue, e così via."
  document.getElementById('tv').nextElementSibling.innerHTML = "Non sono mai stata una bambina sportiva (scioccante, lo so), ho preferito la tv. Buffy l'ammazzavampire è ciò che mi ha insegnato come comunicare in un inglese non rigido e che proveniva direttamente dai libri scolastici, perchè lo amavo così tanto che ho sentito il dovere di guardarlo e riguardarlo in lingua originale con i sottotitoli. Anche se guardo ancora sci-fi e telefilm drammatici, negli ultimi anni mi sono concentrata sulle sitcom e commedie, che trovo un ottimo modo di rilassarsi nel tempo libero, con tutta la loro leggerezza e ottimismo. Friends, Will&Grace, Scrubs, Una Mamma per Amica, Leverage e altri vecchi show spesso accompagno i miei pasti: è inspiegabile ma c'è sempre 'troppo da fare' per guardare un film da 90 minuti, mentre 5 episodi di fila di una sitcom sono okay."
  document.getElementById('books').innerHTML = " libri";
  document.getElementById('books').nextElementSibling.innerHTML = "Non ero soltanto una bambina da tv, ero anche quella che si dimenticava del mondo mentre leggeva finchè qualcuno non riusciva a recuperarne l'attenzione. Ho sempre letto troppo in fretta quindi mi ritrovavo sempre con nulla di nuovo da leggere: Jurassic Park, il primo libro che mi è stato regalato, mi è durato circa sei ore. Le superiori erano dedicate a Stephen King, Terry Pratchett e il Signore Degli Anelli, che avrò riletto un milione di volte. Anche i manga, nessuna vergogna nelle letture leggere e a volte ridicole, anche se c'è stato soltanto Gintama in quel campo negli ultimi anni.";
  document.getElementById('data').innerHTML = " analisi dei dati";
  document.getElementById('data').nextElementSibling.innerHTML = "questo è uno sviluppo recente, ma avendo avuto l'opportunità di seguire il corso di specializzazione google sull'analisi dei dati ho scoperto di amare l'idea di trovare modi di risolvere problemi tramite la ricerca, di lavorare su come ottenere i dati e quali, un qualcosa che avevo già intravisto all'università ma non avevo visto messo in pratica (non fare domande che suggeriscono le risposte, non farti guidare dai tuoi pregiudizi), e poi trovare come ottenere quei dati, sistemarli, analizzarli, farne una presentazione... Lo trovo incredibilmente interessante e utile, non solo per il marketing ma anche per le risorse umane, e anche se al momento non ho accesso a grandi database o strumenti necessari per farlo, ho tutte le intenzione di continuare ad approfondire l'argomento!";
  document.getElementById('ps').innerHTML = " photoshop";
  document.getElementById('ps').nextElementSibling.innerHTML = "questo è abbastanza ovvio ma dovevo menzionarlo qui almeno una volta: come potete notare guardando la maggior parte degli sfondi in questo portfolio, amo prendere foto, dipinti, con il permesso dell'autore, e modificarli per farne sfondi, copertine, o semplicemente gifs!";
  document.getElementById('studi').innerHTML = " studi";
  document.getElementById('studi').nextElementSibling.innerHTML = "ho una laurea in scienze e tecniche psicologiche e una magistrale in psicologio dello sviluppo e dei processi socio-lavorativi (e un grande amore per la clinica). Sto ancora aspettando di poter fare il mio tirocinio! La verità è che porto con me tutto ciò che ho studiato, e che a volte ho persino dibattuto con amici a proposito di personaggi di telefilm (ora, è soltanto per divertimento e sono tutte ipotesi! So che personaggi immaginari non possono essere analizzati davvero!) e di come le persone reali non reagirebbe così a ciò che gli accade - ciò mi ha portato a scrivere una tesi sul disturbo post-traumatico proprio per la rabbia contro il modo in cui i traumi venivano trattati con leggerezza dai media (e naturalmente anche per il mio enorme interesse nell'argomento). Non c'è probabilmente bisogno di dire che leggo anche troppo su qualsiasi argomento mi colpisca, anche se le mie fonti di apprendimento preferite sono altre persone che condividono le loro lotte e i loro percorsi, dandomi un punto di vista sulla terapia e sulle aspettative che la società ha verso di loro che nessun libro potrebbe offrirmi."

  document.getElementById('description').innerHTML = "se non hai cliccato su nulla, ecco un bel paesaggio per te."

  document.getElementById('ido').innerHTML = "che altro dire:"
  document.getElementById('ido1').innerHTML = "ho tradotto un fumetto dall'italiano all'inglese";
  document.getElementById('ido2').innerHTML = "sono una caregiver part-time per un anziano (il momento della giornata in cui la maggior parte degli hobby discussi sopra avvengono: lui vuole guardarsi un po' di tv? Io nel frattempo modifico immagini o gioco a qualcosa)";
  document.getElementById('ido3').innerHTML = "seguo classi online per imparare nuovi argomenti o migliorare vecchie abilità";
  document.getElementById('thanks').innerHTML = "grazie per l'attenzione!";
  document.getElementById('thanks').style.fontFamily = "dancing script";
  document.getElementById('credits').innerHTML = "crediti:";
  document.getElementById('p1').innerHTML = "icone: fontawesome<br>fonts da google e 1001fonts.";
  document.getElementById('p2').innerHTML = "script per le animazioni quando si scrolla da <a href='http://jsfiddle.net/ravimallya/mhfcwyk8/1/' target='_blank'>@ravimallya</a>";
}

function eng() {
  document.getElementById('title').innerHTML = 'behind the screen';
  document.getElementById('tale1').innerHTML = 'a';
  document.getElementById('tale2').innerHTML = 'tale';
  document.getElementById('tale3').innerHTML = 'of';
  document.getElementById('tale4').innerHTML = 'hyperfocusing';
  document.getElementById('intro-to-bio').innerHTML = 'If you are the type of person who likes to go the extra mile and get to know <em>who</em> is working for them personally, or simply someone who saw this portfolio and got curious about who is "Kali", this is the page for you!';
  document.getElementById('intro-to-bio2').innerHTML = "Now, the tone may not always be the most serious, it wouldn't be a honest 'about me' if it didn't convey my sense of humor or didn't show frivolous interests, but I hope this page will also show that when I love something, doesn't matter if it's a hobby or a job, I <em>love</em> it and I will give it my best.<br>If you take anything away from this page, let it be that I dedicate all of myself to everything I do.";
  document.getElementById('click').innerHTML = "Click on a topic to learn more!";
  document.getElementById('clickandscroll').innerHTML = "Click on a topic and scroll to learn more!";
  document.getElementById('steam').nextElementSibling.innerHTML = "once I start playing a new game, often rpgs, I'm dead to the world just as much as when I'm creating blogs: Skyrim, Dragon Age, Final Fantasy, Tomb Raider... I prefer long games, possibly with sequels that involve the same characters and the same themes, and that aren't too hard to play because somehow growing up I lost most of my gaming skills. I used to be fantastic at shooting games and fighting ones, now I can't even look in Call of Duty's direction!";
  document.getElementById('dog').innerHTML = "animals";
  document.getElementById('dog').nextElementSibling.innerHTML = "not going to lie, 95% of my instagram is dedicated to pages about dogs, cats, otters and cute animals because they just make my day better. Need to recharge? Some happy music and a few dogs in costumes and I'm good to go!";
  document.getElementById('bread').innerHTML = "food";
  document.getElementById('bread').nextElementSibling.innerHTML = "if there is one thing that makes me the most stereotypical Italian is my strong relationship with food. You know those jokes about how italian grandmothers will ask you to get the chicken leg from a chicken that has lived in a specific mountain and that was then preserved in secret place, in the dark, for no less than six months? I'm that grandmother. I'm that specific about what food I want, I'm going to enjoy every single second of every meal I have, as long as it's composed by dishes I like and hate every second of its something I don't like much but choose to eat because healthy. No in between.";
  document.getElementById('writing').innerHTML = " writing";
  document.getElementById('writing').nextElementSibling.innerHTML = "I found myself writing original (admittedly very clichè-y) stories as a middle-schooler, which evolved into writing fanfiction (aka: I hate what happened to that character, I'm going to write what I think would be a better path for them), which turned into collaborative writing on tumblr, having too much fun creating characters that fit in a pre-existing world and coming up with their inner world too, development and reactions to what other people wrote. Sort of like writing tvshows except that instead of focusing on one character I ended up making dozens, and a few of them were written for at least six years straight. That also led me to wanting each character to have its own blog with a specific look - and I met HTML and CSS for the first time! ";
  document.getElementById('blogging').nextElementSibling.innerHTML = "I don't only like tumblr because of the opportunities it offers in terms of learning skills - web designers and coders offering tutorials for free out of passion for their jobs, me learning English through writing - but because of the chance it gives to connect with people all over the world and learn about different cultures, about communities directly from people who belong in them, and rare obscure things that wouldn't be discussed anywhere else."
  document.getElementById('lang').innerHTML = "languages";
  document.getElementById('lang').nextElementSibling.innerHTML = "I'm Italian, English is a second language and I'm starting to give a first look at Spanish grammar lessons, though there are only so many hours in a day and I gave priority to coding. I admire and want to emulate people who know 5-6 languages, because I know how many doors English opened for me. It led me to tumblr, which led me to not only a better understanding of many subjects including psychology, but also to take an interest in web designing, in Photoshop, and in following courses that had me noticing other topics such as data analysis and human resources. It also made me write more, reminded me I'm curious about other languages, and so on."
  document.getElementById('tv').nextElementSibling.innerHTML = "I was never the sports-kid (shocking, I know), favoring tv instead. It's actually Buffy the Vampire Slayer and its dvds that taught me how to actually communicate in an English that wasn't stiff and directly from schoolbooks, because I loved it so much that I just had to listen to it in original language with Italian subs. While I still watch sci-fi and less than happy tvshows, though, in the last couple of years I focused mostly on sitcoms and comedies, as I find them a great way to relax in my spare time, with all their silliness and hope. Rewatches of Friends, Will&Grace, Scrubs, Gilmore Girls, Leverage, and other early 2000s shows often accompany my meals. Somehow there is always too much to do to watch a 90min movie, but somehow watching 5 episodes of a 20 minutes sitcom in a row works."
  document.getElementById('books').innerHTML = " books";
  document.getElementById('books').nextElementSibling.innerHTML = "I wasn't just the tv-kid, I was also the kid who forgot to look up from her books unless someone managed to get her attention. I read too fast, though, so I always ended up with nothing new to read: Jurassic Park, the first book that was directly gifted to me, lasted about six hours. High school was all about Stephen King and Terry Pratchett, as well as re-reading Lord of the Rings about a million times. Manga, too, no shame in reading light, at time ridiculous stories, though when it comes to them for the past few years there was only Gintama.";
  document.getElementById('data').innerHTML = " data analytics";
  document.getElementById('data').nextElementSibling.innerHTML = "this is a recent development, but having had the opportunity to take the google Data Analytics specialization I found out I love the idea of coming up with ways to solve a problem through research, work on how to gather the data and what data, which is something that I had already read about during my university classes but I hadn't seen put in practice (don't ask leading questions, make sure you are not guided by your bias etc.), then actually find ways to gather said data, clean it, analyze it, make a presentation... I find it incredibly interesting as well as useful (not only for marketing reasons but for human resources) and while I don't have access to big databases and tools necessary for it, I still plan on learning more about it!";
  document.getElementById('ps').innerHTML = "photo editing";
  document.getElementById('ps').nextElementSibling.innerHTML = "this one was kinda obvious but it had to be mentioned at least once: as you can tell from most of the backgrounds used in this portfolio, I love taking photos, paintings, obviously with the permission of the owner, and editing them to make backgrounds, covers, or simply gifs!";
  document.getElementById('studi').innerHTML = "studies";
  document.getElementById('studi').nextElementSibling.innerHTML = "I have a 3 years degree in psychological sciences and techniques and took a 2 years specialization in psychology of social and workplace-related processes and of development (although I love clinical too). Still waiting to be able to start my internship! <br>Truthfully I carry everything I study with me and end up having long debates with friends even about fictional characters (now, that's just for fun and hypothetical! I know you can't actually analyze them!) and talk about how a real person would not react the way they do - which brought me to write a thesis about PTSD out of annoyance towards how lightly it was treated in media (and of course over my extreme interest in the topic).<br>Needless to say I read up far too much about every possible topic that hits me, though my favorite sources of learning are always the people who share their struggles and journeys, giving me a completely different point of view on therapy and society expectations that no book can offer."

  document.getElementById('description').innerHTML = "if you haven't clicked on anything, here's a nice landscape for you."

  document.getElementById('ido').innerHTML = "what else:"
  document.getElementById('ido1').innerHTML = "I translated a comic book from Italian to English";
  document.getElementById('ido2').innerHTML = "I'm a part-time caregiver for an elderly man (this would be the time when most of the hobbies above happen: he feels like watching tv? I can edit pictures on photoshop or play a game)";
  document.getElementById('id3').innerHTML = " I take online classes to learn new interesting subjects or to advance in old ones";
  document.getElementById('thanks').innerHTML = "thank you for your attention!"
  document.getElementById('credits').innerHTML = "credits:";
  document.getElementById('p1').innerHTML = "icons: fontawesome <br> fonts: google fonts and 1001 fonts";
  document.getElementById('p2').innerHTML = "script for animations happening on scroll from <a href='http://jsfiddle.net/ravimallya/mhfcwyk8/1/' target='_blank'>@ravimallya</a>";
}